### ISSUE TITLE
> babel-node ./bin/run  server.js:53 app.use(serve('public'));         ^  ReferenceError: serve is not defined

### ISSUE THREAD

**Issue by cheerego** [chentsulin/generator-koa2#10]
when npm start,throw a error
`server.js:53 app.use(serve('public'));         
                                    ^  ReferenceError: serve is not defined`
I found that server.js lost a module and I add 
`import serve from 'koa-static'`

**Comment by ghost** [comment]
@cheerplaceless You are right.

**Comment by chentsulin** [comment]
Published a new version `v0.2.1`. Thanks you all : )
